### ISSUE TITLE
Paper experiment configurations

### ISSUE THREAD

**Issue by arielge** [zhanglu-cst/ClassKG#1]
Hi,
I see the dataset configurations are different from the parameters described in the paper. Could you share the configuration files used for the paper?
Thanks!

**Comment by zhanglu-cst** [comment]
> 

Hi,  for each data set, we subsequently made some parameter adjustments to achieve higher performance, such as training epochs, etc. You can follow the experimental settings in the code. 

By the way , I may not check GitHub often. If you need to communicate in time, you can contact me via email: l_zhang19@fudan.edu.cn  

Thanks!

**Comment by zhanglu-cst** [comment]
Thanks for attention
